### PR TITLE
Accept and return an array

### PR DESCRIPTION
**Pull request by mvasilkov**
Hi,

This patch makes the function accept (and return) an array of lines, in addition to a long string. I hope that's OK.

Also, some trivial cleanups:

* Move `/\s+/` to a variable, similar to `/^\s+/`
* Test names are in the first person

### CODE REVIEW

**Review by MoOx — CHANGES_REQUESTED** [review]
Please remove all change related to Es2015 change.   This  library is transpired using babeljs to es5.

**Comment by mvasilkov** [comment]
@MoOx oh man, I didn't realize that those commits were going into this pull request! Sorry!

Those changes weren't meant for being included at all, I was just fixing my own shit locally.

Please disregard this mess. I'll make a proper clean pull request tomorrow, when I'm back on a working PC.

**Comment by MoOx** [comment]
You don't need to cut a new pull request, you can clean the history here and reopen it!

**Comment by MoOx** [comment]
Anyway I am ok for this small improvement :)

**Comment by mvasilkov** [comment]
BTW sorry that I'm reopening this thread, but you wrote earlier:

> This library is transpired using babeljs to es5.

But the package, as published to the npm registry, contains only the original ES6 code, with `=>` and all?

**Comment by MoOx** [comment]
Oh you are right. My bad. What version of node you need to support?

**Comment by mvasilkov** [comment]
I'm using it client side, and my toolchain presently just runs UglifyJS, whereas it should really do Babel --es2015 (and it's not my code even, it's the Next.js server which I won't be forking anytime soon).

I realize that it's basically my tooling problem not the library's, but since you mentioned transpiling earlier, I wanted to check since it could fix my use case, too.

**Pull request closed without merging**
